on:
  push:
    branches: [dev]
jobs:
  build:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Run integration test
        run: make integration-test-dev

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: './integration-test/reports/*.xml'
          check_name: "HTTP Client Integration test"
          job_summary: true
          detailed_summary: true
